GameColor.Difficulty.Beginner = color("0,1,1,1")
GameColor.Difficulty.Easy = color("1,1,0,1")
GameColor.Difficulty.Medium = color("1,0,0.5,1")
GameColor.Difficulty.Hard = color("0,1,0,1")
GameColor.Difficulty.Challenge = color("1,0.5,1,1")
GameColor.Difficulty.Edit = color("1,1,1,1")